# Cozy Matcha - Kitty Terminal Theme
# Guárdalo en ~/.config/kitty/cozy-matcha.conf
# y añádelo a tu kitty.conf general con: include cozy-matcha.conf

background #1e221f
foreground #d4e0d7
cursor     #aebf9c
cursor_text_color #1e221f
selection_background #324632
selection_foreground #d4e0d7

# Black
color0 #171a18
color8 #a4b5a9

# Red
color1 #d07878
color9 #d07878

# Green
color2 #8da38c
color10 #b1ccad

# Yellow
color3 #aebf9c
color11 #aebf9c

# Blue
color4 #799478
color12 #799478

# Magenta
color5 #afc9ab
color13 #afc9ab

# Cyan
color6 #92ab8c
color14 #92ab8c

# White
color7 #d4e0d7
color15 #ffffff
